### ISSUE TITLE
how does rss work?

### ISSUE THREAD

**Issue by kentdtran** [finaldie/auto-news#107]
I entered the rss endpoints but I cant see any new articles or documents pulled from rss?

how do I create an RSS toread?

Can you explain what should happen?

also the af_pull.py is failing because there is no reddit authentication set up. I dont want to monitor reddit. i removed reddit and twitter from CONTENT_SOURCES but it still trying to pull from there :(

**Comment by finaldie** [comment]
Thanks for raising the question, From your description I feel it mainly because of pulling failed , and RSS step hasn't start, if that's the case, I will check later to see the bypass path.

**Comment by kentdtran** [comment]
yes it was because i didnt rebuild the docker images to deploy the updated code
does rss need to be pulled on a schedule or can it get the articles the moment the feed is updated?

**Comment by kentdtran** [comment]
i think you should have exception handlers in each task so that one fail doesnt fail all the others down the path for pulling

**Comment by finaldie** [comment]
> does rss need to be pulled on a schedule or can it get the articles the moment the feed is updated?

RSS pulled on schedule (every hour), in case you want to reduce the interval, modify the schedule in this [dag](https://github.com/finaldie/auto-news/blob/main/dags/news_pulling.py#L43) and build a new image to deploy


> i think you should have exception handlers in each task so that one fail doesnt fail all the others down the path for pulling

I rechecked, and yes, there is protection for each source pulling, so even if the Reddit path failed, it wouldn't impact other sources ([ref](https://github.com/finaldie/auto-news/blob/main/src/af_pull.py#L132)). At this moment, I feel it may be related to your RSS Inbox setup, if you followed this [wiki](https://github.com/finaldie/auto-news/wiki/Docker-Installation#ui-set-up-notion-tweetrssreddit-list), it should be fine.

However, some RSS cannot be pulled programmatically (aka Robot/Api); it only allows access via Browser. I am not sure whether you are in this case, but if you don't mind sharing your RSS, I can help to verify offline. Otherwise, you may want to wait for my next release, which I have an ongoing experiment to deal with this issue.
