### ISSUE TITLE
Billing

### ISSUE THREAD

**Issue by theobouwman** [finaldie/auto-news#38]
Great project.

Do you have an estimate about the billing usage of OpenAI Reddit and Twitter API?

**Comment by finaldie** [comment]
Thank you @theobouwman 

For billing usage:
- OpenAI: For my case, Sep with $4.5
- Reddit: Free
- Twitter API: I give up on it at this moment since it's too expensive and with many limitations.

Besides the external services billing, the server which auto-news runs also may require some cost, for example, if we deploy it to the cloud provider (e.g. AWS, GCP, Azure, DO, Linode, etc), the prices may vary depending on which plan we choose. (For me, I deployed it to my home server, so it may be hard to measure the cost)

I hope the information provided above is helpful to you.

Example of my `OpenAI` API billing usage (Sep):
![image](https://github.com/finaldie/auto-news/assets/1088543/c5b5bd0b-976d-4cb9-9fa9-1ed79ed5965f)
