### ISSUE TITLE
Question: What is TODO in ToRead section? And what does the Journal do?

### ISSUE THREAD

**Issue by zuenko** [finaldie/auto-news#58]
I'm trying to figure out what it means, that is, what am I supposed to put into the journals? I've tried various methods, including dropping in articles, article titles, and the outcome is always different. Also, when I inserted an entire article into a journal, it generated a lot of TODOs, and I'm not entirely sure of their purpose. It would be great to get some clarification, thanks.

**Comment by finaldie** [comment]
@zuenko

Sorry for the confusion, let me take a time to explain it more, the journal inbox is used for user to input random journal notes, say:
* Everyday we may drop 3 quick notes into the journal inbox
* At end of the day, the journal DAG will be triggered and collect all the unprocessed notes and refine/organize/formating as along as generate those insights/takeaways/actions(todos)

Above is the basic functionality of the Journal DAG, the confusion you described above is why we are seeing some `action items` being generated along with the journal notes, that's another recent feature that generates the action items `every hour` (based on Journal notes) then insert into the `TODOs`, so that we will have more action items generated timely rather than wait until the end of the day.

The logic is here, https://github.com/finaldie/auto-news/blob/main/src/af_action_pull.py#L78

I hope that a little help, and let me know if anything is not clear.
